package pojos;
// Generated 14 feb 2022 13:49:31 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private Integer idLibro;
	private String titulo;
	private int numEjemplares;
	private String editorial;
	private int numPaginas;
	private int anioEdicion;
	private Set prestamos = new HashSet(0);

	public Libro() {
	}

	public Libro(String titulo, int numEjemplares, String editorial, int numPaginas, int anioEdicion) {
		this.titulo = titulo;
		this.numEjemplares = numEjemplares;
		this.editorial = editorial;
		this.numPaginas = numPaginas;
		this.anioEdicion = anioEdicion;
	}

	public Libro(String titulo, int numEjemplares, String editorial, int numPaginas, int anioEdicion, Set prestamos) {
		this.titulo = titulo;
		this.numEjemplares = numEjemplares;
		this.editorial = editorial;
		this.numPaginas = numPaginas;
		this.anioEdicion = anioEdicion;
		this.prestamos = prestamos;
	}

	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getNumEjemplares() {
		return this.numEjemplares;
	}

	public void setNumEjemplares(int numEjemplares) {
		this.numEjemplares = numEjemplares;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public int getNumPaginas() {
		return this.numPaginas;
	}

	public void setNumPaginas(int numPaginas) {
		this.numPaginas = numPaginas;
	}

	public int getAnioEdicion() {
		return this.anioEdicion;
	}

	public void setAnioEdicion(int anioEdicion) {
		this.anioEdicion = anioEdicion;
	}

	public Set getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set prestamos) {
		this.prestamos = prestamos;
	}

}
